### ISSUE TITLE
Add SCSS Linter

### ISSUE THREAD

**Issue by connorshea** [AnthonySuper/ImageHex#323]
https://github.com/brigade/scss-lint

Add the following to the `Gemfile`:

``` ruby
##
# Configurable tool for writing clean and consistent SCSS
# Config file: `.scss_lint.yml`
# Run linter with `rake scss_lint`
# https://github.com/brigade/scss-lint
gem 'scss_lint', require: false
```

Add the following to the `Rakefile` to enable `rake scss_list`:

``` ruby
require 'scss_lint/rake_task'

SCSSLint::RakeTask.new
```

Here's a `.scss-lint.yml` to start with:

``` yml
scss_files: 'app/assets/stylesheets/**/*.scss'

linters:
  # Always indent with 2 spaces.
  Indentation:
    width: 2

  # Don't allow `color: white`, should be `color: #fff`.
  ColorKeyword:
    enabled: true

  # Require empty lines between selector blocks.
  EmptyLineBetweenBlocks:
    enabled: true

  # Throw a warning for selectors without properties.
  EmptyRule:
    enabled: true

  # If possible, hex colors should use 3 characters, e.g. `#fff` instead of `#ffffff`.
  HexLength:
    enabled: true
    style: short

  # Color format should be lowercase to differentiate between numbers and letters (e.g. `#O0O` vs. `#o0o`).
  HexNotation:
    enabled: true
    style: lowercase

  # Selector style like `.selector-name`.
  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase

  # Require a single space before the brace for selector declarations, e.g. `.selector-name {`.
  SpaceBeforeBrace:
    enabled: true
    style: space

  # Don't include units with 0 values, e.g. `0px` vs. just `0`, the latter is slightly more performant.
  ZeroUnit:
    enabled: true
```

A list of default linters is available [here](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md) and the default configuration is available [here](https://github.com/brigade/scss-lint/blob/master/config/default.yml).
